version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    depends_on:
      - zookeeper

  druid-coordinator:
    image: apache/druid:26.0.0
    ports:
      - 8081:8081
    environment:
      DRUID_HOSTNAME: druid-coordinator
    depends_on:
      - zookeeper
      - kafka

  druid-broker:
    image: apache/druid:26.0.0
    ports:
      - 8082:8082
    environment:
      DRUID_HOSTNAME: druid-broker
    depends_on:
      - zookeeper
      - kafka

  druid-historical:
    image: apache/druid:26.0.0
    ports:
      - 8083:8083
    environment:
      DRUID_HOSTNAME: druid-historical
    depends_on:
      - zookeeper
      - kafka

  druid-middlemanager:
    image: apache/druid:26.0.0
    ports:
      - 8091:8091
    environment:
      DRUID_HOSTNAME: druid-middlemanager
    depends_on:
      - zookeeper
      - kafka

  druid-overlord:
    image: apache/druid:26.0.0
    ports:
      - 8090:8090
    environment:
      DRUID_HOSTNAME: druid-overlord
    depends_on:
      - zookeeper
      - kafka

  chitragupta_producer:
    image: com.chitragupta/chitragupta-producer:latest
    depends_on:
      - kafka
    environment:
      KAFKA_URL: kafka:9092
      REDIS_URL: redis://redis:6379/0
      MAX_USER_COUNT: 100L
      MAX_EVENT_COUNT: 26 # represents letters A to Z

  chitragupta_enricher:
    image: com.chitragupta/chitragupta-enricher:latest
    depends_on:
      - kafka
      - redis
    environment:
      KAFKA_URL: kafka:9092
      REDIS_URL: redis://redis:6379/0

  chitragupta_persister:
    image: com.chitragupta/chitragupta-persister:latest
    depends_on:
      - kafka
      - chitragupta_enricher
    volumes:
      - /tmp:/tmp
    environment:
      KAFKA_URL: kafka:9092
      REDIS_URL: redis://redis:6379/0

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - 9000:9000
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092